#!/usr/bin/env bash
# Lists current directory files showing only part after first dash
for file in *; do
    if [[ ! "$file" =~ ^\. ]]; then  # Skip hidden files
        echo "${file#*-}"
    fi
done
